"use client";
import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";

export default function WikiPage() {
  const { username } = useParams();
  const router = useRouter();
  const [page, setPage] = useState<any>(null);
  const [notFound, setNotFound] = useState(false);

  useEffect(() => {
    fetch(`http://localhost:5000/api/page/${username}`)
      .then((r) => r.json())
      .then((data) => {
        if (data.page) setPage(data.page);
        else setNotFound(true);
      });
  }, [username]);

  if (notFound) return (
    <main style={{ maxWidth: 680, margin: "80px auto", padding: "0 24px", fontFamily: "Georgia, serif" }}>
      <h1 style={{ fontWeight: 400 }}>Page not found</h1>
      <p style={{ color: "#666" }}>No WikiGamer page exists for <em>{username}</em> yet.</p>
      <button onClick={() => router.push("/")} style={{ marginTop: 16, cursor: "pointer" }}>← Go back</button>
    </main>
  );

  if (!page) return (
    <main style={{ maxWidth: 680, margin: "80px auto", padding: "0 24px", fontFamily: "Georgia, serif", color: "#666" }}>
      Loading...
    </main>
  );

  return (
    <main style={{ maxWidth: 680, margin: "0 auto", padding: "40px 24px", fontFamily: "Georgia, serif" }}>
      <p style={{ fontSize: 12, color: "#666", marginBottom: 8 }}>
        ← <span style={{ cursor: "pointer", color: "#3366cc" }} onClick={() => router.push("/")}>WikiGamer</span>
      </p>
      <h1 style={{ fontSize: 32, fontWeight: 400, borderBottom: "1px solid #ddd", paddingBottom: 8, marginBottom: 16 }}>
        {page.username}
      </h1>

      {/* Render each section from the generated page */}
      {page.sections?.map((section: any) => (
        <div key={section.title} style={{ marginBottom: 24 }}>
          <h2 style={{ fontSize: 20, fontWeight: 400, borderBottom: "1px solid #eee", paddingBottom: 4, marginBottom: 8 }}>
            {section.title}
          </h2>
          <p style={{ lineHeight: 1.7, fontSize: 14 }}>{section.content}</p>
        </div>
      ))}

      <div style={{ marginTop: 32, borderTop: "1px solid #ddd", paddingTop: 16, fontSize: 12, color: "#888" }}>
        Generated by WikiGamer &nbsp;|&nbsp;
        <span style={{ color: "#3366cc", cursor: "pointer" }}>Claim this page</span>
      </div>
    </main>
  );
}